<?php

namespace AppBundle\Repository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends \Doctrine\ORM\EntityRepository
{
    public function findActivityWhereLabelInclude($label)
    {
        $activity = $this->getEntityManager()->createQuery('
            SELECT a FROM AppBundle:Activity a
            WHERE a.label LIKE :label
        ')
            ->setParameter('label', '%'. $label . '%')
            ->getResult()
        ;

        return $activity;
    }
}
